image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
secrets:
  - 1cc83501-b3f6-496d-ad90-8f9f1c295580
sources:
  - git@git.sr.ht:~glorifiedgluer/glorifiedgluer.com
environment:
  site: glorifiedgluer.com
  NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
  - check_branch: |
      cd glorifiedgluer.com
      if [ "$(git rev-parse master)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - blog: |
      cd glorifiedgluer.com
      nix build
      nix run .#hut -- pages publish ./result/site.tar.gz \
        --domain $site \
        --not-found 404.html
